## 공통(개인)과제: CTQ3 두께 or CTQ5 통기도품질예측모형

- 1) 데이터 준비: 불러오기(csv, excel) --> shape, info(), keys(), head(), tail()
- 2) 데이터 전처리: 불필요한 column 삭제, column명 처리, 새로운 column 생성(e.g. CTQ 5 값 500 기준으로 그룹 구분),  'Model No.'One-Hot-encoding 등
- 3) 탐색적 분석(EDA): countplot, distplot, pairplot(seaborn, matplotlib)
- 4) 탐색적 분석(통계): 개별 변수별 unique(), value_counts()...기초통계(describe, mean, std...), 상관관계, T-test('Model No.'별로 CTQ의 차이가 유의한 지), 'Model No.'별 groupby() 함수 사용 등
- 5) feature 선택: CTQ3 or CTQ5 예측에 도움이 되는 x값들만 선별
- 6) Model 선택: LinearRegression
- 7) 분석 결과 해석: R^2 값 확인, 독립 변수별 계수 값 및 유의 수준 확인 등

### 1) 데이터 불러오기

In [1]:
import pandas as pd

In [3]:
data = pd.read_excel('생산기술원데이터.xlsx') # excel파일 그대로 분석할 경우
data.to_csv('CTQ.csv')  # excel file을 csv파일로 바꾸어서 분석할 경우

In [5]:
data = pd.read_csv('CTQ.csv')
print(data.shape)
data.head()

(1571, 244)

,Unnamed: 0,LINE,LOTID,Data_Time,Model No.,[A]Zone1_Feature1_SV,[A]Zone1_Feature1_PV,[A]Zone1_Feature2_PV,[A]Zone1_Feature3_PV,[A]Zone2_Feature4_SV,...,CTQ 2_LSL,CTQ 3,CTQ 3_USL,CTQ 3_LSL,CTQ 4,CTQ 4_USL,CTQ 4_LSL,CTQ 5,CTQ 5_USL,CTQ 5_LSL
0,0,R13,CDRC19060690,2019-06-14 00:48:00,AKT30680983,65,644.571429,1299.0,1350.0,132,...,75,17.850000,20.5,15.5,14.0850,16,13,643.333333,950,450
1,1,R13,CDRC19060691,2019-06-14 00:58:00,AKT30680983,65,633.428571,1299.0,1350.0,132,...,75,17.850000,20.5,15.5,14.0850,16,13,643.333333,950,450
2,2,R13,CDRC19060692,2019-06-14 01:08:00,AKT30680983,65,626.625000,1299.0,1350.0,132,...,75,18.525000,20.5,15.5,14.2975,16,13,675.666667,950,450
3,3,R13,CDRC19060693,2019-06-14 01:18:00,AKT30680983,65,623.428571,1299.0,1350.0,132,...,75,18.525000,20.5,15.5,14.2975,16,13,675.666667,950,450
4,4,R13,CDRC19060694,2019-06-14 01:28:00,AKT30680983,65,621.500000,1299.0,1350.0,132,...,75,18.608333,20.5,15.5,14.5750,16,13,815.333333,950,450